# Generated by Django 5.1.3 on 2025-01-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_rename_contact_number_emergency_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='emergency_contact',
            new_name='emergency_number',
        ),
    ]
